Changes to exit code 1 when compiler has errors (#1424)
## Summary

^^^



## Checklist
- [x] Added Unit Tests
- [ ] Covered by existing CI
- [ ] Integration tested
- [ ] Documentation update

Tested on machine:

```
(feb6) davidhan@Davids-MacBook-Pro-2: ~/zipline_mill/feb5/zipline $ zipline compile

/Users/davidhan/zipline_mill/feb5/zipline already on python path.
Pulling configuration from /Users/davidhan/zipline_mill/feb5/zipline/teams.py

Join-s:
  ➕ Added test.data.v1__0

GroupBy-s:
  ➕ Added test.data.group_by_v1__0


(feb6) davidhan@Davids-MacBook-Pro-2: ~/zipline_mill/feb5/zipline $ echo $?
0
(feb6) davidhan@Davids-MacBook-Pro-2: ~/zipline_mill/feb5/zipline $ 
(feb6) davidhan@Davids-MacBook-Pro-2: ~/zipline_mill/feb5/zipline $ 
(feb6) davidhan@Davids-MacBook-Pro-2: ~/zipline_mill/feb5/zipline $ 
(feb6) davidhan@Davids-MacBook-Pro-2: ~/zipline_mill/feb5/zipline $ code .
(feb6) davidhan@Davids-MacBook-Pro-2: ~/zipline_mill/feb5/zipline $ zipline compile

/Users/davidhan/zipline_mill/feb5/zipline already on python path.
Pulling configuration from /Users/davidhan/zipline_mill/feb5/zipline/teams.py
ValueError: join test.data.v1__0's underlying group_by test.data.group_by_v1__0 uses unwindowed aggregations [
Aggregation(inputColumn='purchase_price', operation=13, argMap={'k': '10'}, windows=None, buckets=None, tags=None)
] 
                    on unbounded event sources: [
Source(events=EventSource(table='data.purchases', topic=None, query=Query(selects=OrderedDict({'user_id': 'user_id', 'purchase_price': 'purchase_price'}), wheres=None, startPartition=None, endPartition=None, timeColumn='ts', setups=None, mutationTimeColumn=None, reversalColumn=None, partitionColumn=None, partitionFormat=None, partitionInterval=None, partitionLag=None, subPartitionsToWaitFor=None, clustered=None), isCumulative=None), entities=None, joinSource=None, modelTransforms=None)
]. 
                    Please set a start_partition on the source, or a window on the aggregation.
ValueError: group_by test.data.group_by_v1__0 uses unwindowed aggregations [
Aggregation(inputColumn='purchase_price', operation=13, argMap={'k': '10'}, windows=None, buckets=None, tags=None)
] 
                    on unbounded event sources: [
Source(events=EventSource(table='data.purchases', topic=None, query=Query(selects=OrderedDict({'user_id': 'user_id', 'purchase_price': 'purchase_price'}), wheres=None, startPartition=None, endPartition=None, timeColumn='ts', setups=None, mutationTimeColumn=None, reversalColumn=None, partitionColumn=None, partitionFormat=None, partitionInterval=None, partitionLag=None, subPartitionsToWaitFor=None, clustered=None), isCumulative=None), entities=None, joinSource=None, modelTransforms=None)
]. 
                    Please set a start_partition on the source, or a window on the aggregation.

Join-s:
  Parsed 1 previously compiled objects.
  Failed to compile 1 files.
  ERROR - /Users/davidhan/zipline_mill/feb5/zipline/joins/test/data.py:
    join test.data.v1__0's underlying group_by test.data.group_by_v1__0 uses unwindowed aggregations [
Aggregation(inputColumn='purchase_price', operation=13, argMap={'k': '10'}, windows=None, buckets=None, tags=None)
] 
                    on unbounded event sources: [
Source(events=EventSource(table='data.purchases', topic=None, query=Query(selects=OrderedDict({'user_id': 'user_id', 'purchase_price': 'purchase_price'}), wheres=None, startPartition=None, endPartition=None, timeColumn='ts', setups=None, 
mutationTimeColumn=None, reversalColumn=None, partitionColumn=None, partitionFormat=None, partitionInterval=None, partitionLag=None, subPartitionsToWaitFor=None, clustered=None), isCumulative=None), entities=None, joinSource=None, 
modelTransforms=None)
]. 
                    Please set a start_partition on the source, or a window on the aggregation.

❗Please fix python errors then retry compilation.

GroupBy-s:
  Parsed 1 previously compiled objects.
  Failed to compile 1 files.
  ERROR - /Users/davidhan/zipline_mill/feb5/zipline/group_bys/test/data.py:
    group_by test.data.group_by_v1__0 uses unwindowed aggregations [
Aggregation(inputColumn='purchase_price', operation=13, argMap={'k': '10'}, windows=None, buckets=None, tags=None)
] 
                    on unbounded event sources: [
Source(events=EventSource(table='data.purchases', topic=None, query=Query(selects=OrderedDict({'user_id': 'user_id', 'purchase_price': 'purchase_price'}), wheres=None, startPartition=None, endPartition=None, timeColumn='ts', setups=None, 
mutationTimeColumn=None, reversalColumn=None, partitionColumn=None, partitionFormat=None, partitionInterval=None, partitionLag=None, subPartitionsToWaitFor=None, clustered=None), isCumulative=None), entities=None, joinSource=None, 
modelTransforms=None)
]. 
                    Please set a start_partition on the source, or a window on the aggregation.

❗Please fix python errors then retry compilation.


(feb6) davidhan@Davids-MacBook-Pro-2: ~/zipline_mill/feb5/zipline $ echo $?
1

```